image: fedora:rawhide

variables:
  DEPENDENCIES:
    gcc
    git
    meson
    glibc-devel
    glib2-devel
    gtk3-devel
    libselinux-devel
    nautilus-devel
    systemd-devel
    httpd
    mod_dnssd
    gettext

build_stable:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build
    - ninja -C _build
    - ninja -C _build dist
  artifacts:
    when: always
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs/"
      - "${CI_PROJECT_DIR}/_build/meson-dist"
