include:
  - remote: 'https://gitlab.gnome.org/Infrastructure/freedesktop-ci-templates/-/raw/e195d80f35b45cc73668be3767b923fd76c70ed5/templates/fedora.yml'
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      job-stage: release
      dist-job-name: "fedora-build"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

variables:
  DEPENDENCIES:
    gcc
    clang
    git
    meson
    glibc-devel
    glib2-devel
    libselinux-devel
    systemd-devel
    httpd
    mod_dnssd
    gettext
    cargo
    rustfmt
  MESON_BUILD_DIR: _build
  TARBALL_ARTIFACT_PATH: "${MESON_BUILD_DIR}/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"
  FDO_DISTRIBUTION_COMPRESSION_FORMAT: zstd:chunked

stages:
  - image
  - check
  - build
  - release

workflow:
  rules:
    # run merge request pipelines, for main or release branches and for manually
    # triggered pipelines (source "web"), but not for translation updates
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" ||
           $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED ||
           $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ||
           $CI_COMMIT_BRANCH =~ /^gnome-.*$/ ||
           $CI_PIPELINE_SOURCE == "web") &&
          $CI_COMMIT_TITLE !~ /^Update.*translation$/


.gnome-user-share.fedora:43:
  variables:
    FDO_DISTRIBUTION_VERSION: 43
    FDO_DISTRIBUTION_TAG: '2025-09-03'

build-fedora-image:
  extends:
  - .fdo.container-build@fedora
  - .gnome-user-share.fedora:43
  stage: image
  rules:
    - changes:
        - .gitlab-ci.yml
        - .gitlab/**/*
      when: always
  variables:
    GIT_STRATEGY: none
    FDO_DISTRIBUTION_PACKAGES: $DEPENDENCIES
    FDO_DISTRIBUTION_EXEC: ".gitlab/image-script.sh"

cargo-fmt:
  extends:
  - .fdo.distribution-image@fedora
  - .gnome-user-share.fedora:43
  stage: check
  needs: 
    - job: build-fedora-image
      optional: true
  interruptible: true
  before_script:
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
  script:
    - meson setup ${MESON_BUILD_DIR}
    - cp ${MESON_BUILD_DIR}/src/config.rs src
    - cargo fmt --all -- --check

fedora-build:
  extends:
  - .fdo.distribution-image@fedora
  - .gnome-user-share.fedora:43
  stage: build
  needs: 
    - job: build-fedora-image
      optional: true
  before_script:
    - rustc -Vv && cargo -Vv && gio --version
  script:
    - meson setup ${MESON_BUILD_DIR}
    - meson dist -C ${MESON_BUILD_DIR}
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "${CI_PROJECT_DIR}/${MESON_BUILD_DIR}/meson-logs/"
      - "${CI_PROJECT_DIR}/${MESON_BUILD_DIR}/meson-dist"
      - "${TARBALL_ARTIFACT_PATH}"
    expire_in: 14 days
