image: fedora:rawhide

variables:
  DEPENDENCIES: gcc gtk3-devel httpd  mod_dnssd intltool itstool libcanberra-devel
                desktop-file-utils libselinux-devel dbus-glib-devel libnotify-devel
                nautilus-devel gettext systemd-devel gnome-common which

build_stable:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - mkdir build
    - cd build
    - NOCONFIGURE=1 ../autogen.sh
    - ../configure --disable-dependency-tracking
    - make
    - make install
    - make distcheck
