image: fedora:rawhide

variables:
  DEPENDENCIES:
    gcc
    git
    meson
    glibc-devel
    glib2-devel
    libselinux-devel
    systemd-devel
    httpd
    mod_dnssd
    gettext
    cargo

workflow:
  rules:
    # run merge request pipelines, for main or release branches and for manually
    # triggered pipelines (source "web"), but not for translation updates
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" ||
           $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ||
           $CI_COMMIT_BRANCH =~ /^gnome-.*$/ ||
           $CI_PIPELINE_SOURCE == "web") &&
          $CI_COMMIT_TITLE !~ /^Update.*translation$/

cargo-fmt:
  image: "rust:slim"
  interruptible: true
  script:
    - rustup component add rustfmt
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --check

build_stable:
  dependencies:
    - cargo-fmt
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build
    - ninja -C _build
    - ninja -C _build dist
  artifacts:
    when: always
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs/"
      - "${CI_PROJECT_DIR}/_build/meson-dist"
    expire_in: 14 days