image: fedora:rawhide

variables:
  DEPENDENCIES: gcc meson glibc-devel glib-devel gtk3-devel
                libselinux-devel nautilus-devel systemd-devel
                httpd mod_dnssd gettext

build_stable:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build
    - ninja -C _build