image: fedora:rawhide

variables:
  DEPENDENCIES: gcc glib-devel gtk3-devel httpd mod_dnssd itstool gettext
                libselinux-devel nautilus-devel gettext systemd-devel

build_stable:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build
    - ninja -C _build